#!/usr/bin/python
# jiri kvita 2020

from __future__ import print_function

cname = 'cquark'
members = [ 'name',  'col', 'mark', 'texName', 'qnum', 'qdenom', 'I3', 'S']

#cname = 'chadron'
#members = ['name', 'quarks', 'texName', 'Q', 'I3', 'S']


print('')
print('')
print('#########################################')
print('class {:}:'.format(cname))
print('  # code generated by PrintGettersAndSetters.py')
inits = ''
for mem in members:
    inits = inits + mem
    if members.index(mem) < len(members) - 1:
        inits = inits + ', '
print('  def __init__(self, {:}):'.format(inits))
for mem in members:
    umem = mem[0].upper() + mem[1:]
    print('    self._{:} = {:}'.format(mem, mem) ) 

print()
for mem in members:
    umem = mem[0].upper() + mem[1:]
    print('  def Get{:}(self): return self._{:}'.format(umem, mem) )
print()
for mem in members:
    umem = mem[0].upper() + mem[1:]
    print('  def Set{:}(self, {:}): self._{:} = {:}'.format(umem, mem, mem, mem) ) 
print()
print('')
