#!/usr/bin/env python3
import argparse
import matplotlib.pyplot as plt
import math
from matplotlib.offsetbox import AnnotationBbox, OffsetImage
import pprint
import re
from pathlib import Path


CLASS_NAME_PATTERN = re.compile(r"^..$")
TRAIN_DIR_PATTERN = re.compile(r"^train_..$")
BAR_TOP_THUMB_CROP_RATIO = 0.6
BAR_TOP_THUMB_ZOOM = 0.28


def count_pngs_in_train(
    root_dir: Path,
    n_to_count: int = -1,
    class_start: str = "30",
    class_end: str = "39",
) -> tuple[dict[str, int], dict[str, Path | None]]:
    if not root_dir.exists() or not root_dir.is_dir():
        raise ValueError(f"Invalid root directory: {root_dir}")

    counts = {}
    first_images = {}
    class_dirs = sorted(
        p
        for p in root_dir.iterdir()
        if p.is_dir()
        and CLASS_NAME_PATTERN.match(p.name)
        and class_start <= p.name <= class_end
    )
    if n_to_count != -1:
        class_dirs = class_dirs[:n_to_count]

    for class_dir in class_dirs:
        train_dirs = [
            p
            for p in class_dir.iterdir()
            if p.is_dir() and TRAIN_DIR_PATTERN.match(p.name)
        ]
        png_count = 0
        first_image = None
        for train_subdir in sorted(train_dirs):
            for png_file in train_subdir.rglob("*.png"):
                png_count += 1
                if first_image is None or str(png_file) < str(first_image):
                    first_image = png_file
        print(f"Counting class {class_dir.name}... {png_count}")
        counts[class_dir.name] = png_count
        first_images[class_dir.name] = first_image
    return counts, first_images


def write_class_counts_py(counts: dict[str, int], output_path: Path) -> None:
    content = "# Auto-generated by count_train_pngs.py\n"
    content += f"class_counts = {pprint.pformat(counts, sort_dicts=False)}\n"
    output_path.write_text(content, encoding="utf-8")


def format_count_short(value: int) -> str:
    if value >= 1_000_000:
        return f"{value / 1_000_000:.1f}M"
    if value >= 1_000:
        return f"{value / 1_000:.1f}k"
    return str(value)


def crop_center_square(image, crop_ratio: float = 0.8):
    """Crop a centered square patch from an image for cleaner thumbnails."""
    height, width = image.shape[:2]
    side = int(min(height, width) * crop_ratio)
    side = max(1, side)
    center_y = height // 2
    center_x = width // 2
    half = side // 2
    y0 = max(0, center_y - half)
    x0 = max(0, center_x - half)
    y1 = min(height, y0 + side)
    x1 = min(width, x0 + side)
    return image[y0:y1, x0:x1]


def plot_class_counts(
    counts: dict[str, int],
    first_images: dict[str, Path | None],
    png_path: Path,
    pdf_path: Path,
    show: bool = False,
) -> None:
    classes = list(counts.keys())
    values = list(counts.values())
    if not classes:
        return

    fig, ax = plt.subplots(figsize=(max(10, len(classes) * 0.5), 6))
    x_positions = list(range(len(classes)))
    bars = ax.bar(x_positions, values, color="green")

    y_max = max(values) if values else 1
    y_top = y_max * 1.75 if y_max > 0 else 1
    ax.set_ylim(0, y_top)

    for x, class_name, bar in zip(x_positions, classes, bars):
        y = bar.get_height()
        ax.text(x, y + y_top * 0.02, format_count_short(int(y)), ha="center", va="bottom", fontsize=8)
        image_path = first_images.get(class_name)
        if image_path is not None and image_path.exists() and y_top > 0:
            image = plt.imread(image_path)
            image_cropped = crop_center_square(image, crop_ratio=BAR_TOP_THUMB_CROP_RATIO)
            image_box = OffsetImage(image_cropped, zoom=BAR_TOP_THUMB_ZOOM)
            ab = AnnotationBbox(
                image_box,
                (x, y + y_top * 0.18),
                frameon=True,
                bboxprops={"edgecolor": "black", "linewidth": 0.5},
            )
            ax.add_artist(ab)

    ax.set_xticks(x_positions)
    ax.set_xticklabels(classes, rotation=90)
    ax.set_xlabel("Class")
    ax.set_ylabel("Number of PNGs")
    ax.set_title("PNG Count per Class")
    fig.tight_layout()
    fig.savefig(png_path)
    fig.savefig(pdf_path)
    if show:
        plt.show()
    else:
        plt.close(fig)


def plot_class_examples_table(
    counts: dict[str, int],
    first_images: dict[str, Path | None],
    png_path: Path,
    pdf_path: Path,
    show: bool = False,
) -> None:
    classes = list(counts.keys())
    if not classes:
        return

    n_rows = len(classes)
    n_cols = 3
    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(14, n_rows * 2.8 + 1),
        squeeze=False,
    )

    for row in range(n_rows):
        for col in range(n_cols):
            axes[row][col].axis("off")

    headers = ["Class", "Count", "First Image"]
    for col, header in enumerate(headers):
        axes[0][col].set_title(header, fontsize=22, pad=16)

    for idx, class_name in enumerate(classes):
        row = idx
        class_ax = axes[row][0]
        count_ax = axes[row][1]
        image_ax = axes[row][2]

        class_ax.text(0.5, 0.5, class_name, ha="center", va="center", fontsize=26)
        count_ax.text(
            0.5,
            0.5,
            format_count_short(counts[class_name]),
            ha="center",
            va="center",
            fontsize=24,
        )
        image_path = first_images.get(class_name)
        if image_path is not None and image_path.exists():
            image_ax.imshow(plt.imread(image_path))
        else:
            image_ax.text(0.5, 0.5, "No PNG", ha="center", va="center", fontsize=20)

    fig.suptitle("Class Table: Name | Count | First Image", fontsize=28)
    fig.tight_layout()
    fig.savefig(png_path)
    fig.savefig(pdf_path)
    if show:
        plt.show()
    else:
        plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Count PNG files for two-character classes by scanning train_?? "
            "subfolders inside each class directory."
        )
    )
    parser.add_argument(
        "--train-dir",
        default="data/by_class",
        help=(
            "Path to dataset root directory. Defaults to data/by_class. "
            "Expected layout: <root>/<2-char-class>/train_??"
        ),
    )
    parser.add_argument(
        "--n-to-count",
        type=int,
        default=-1,
        help="Count only first N classes for debugging. Use -1 to count all classes.",
    )
    parser.add_argument(
        "--class-start",
        default="30",
        help="Start class name (inclusive). Default: 30",
    )
    parser.add_argument(
        "--class-end",
        default="39",
        help="End class name (inclusive). Default: 39",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show plots interactively (default: save only)",
    )
    args = parser.parse_args()

    train_dir = Path(args.train_dir).resolve()
    if args.n_to_count < -1:
        raise ValueError("--n-to-count must be -1 or a non-negative integer")
    if len(args.class_start) != 2 or len(args.class_end) != 2:
        raise ValueError("--class-start and --class-end must be two-character strings")
    if args.class_start > args.class_end:
        raise ValueError("--class-start must be <= --class-end")
    counts, first_images = count_pngs_in_train(
        train_dir,
        n_to_count=args.n_to_count,
        class_start=args.class_start,
        class_end=args.class_end,
    )
    output_path = Path("class_counts.py").resolve()
    plot_png_path = Path("class_counts.png").resolve()
    plot_pdf_path = Path("class_counts.pdf").resolve()
    table_png_path = Path("class_examples_table.png").resolve()
    table_pdf_path = Path("class_examples_table.pdf").resolve()
    write_class_counts_py(counts, output_path)

    total = 0
    for class_name, n in counts.items():
        print(f"{class_name}: {n}")
        total += n
    print(f"TOTAL: {total}")
    print(f"Wrote class dictionary to: {output_path}")
    plot_class_counts(counts, first_images, plot_png_path, plot_pdf_path, show=args.show)
    print(f"Saved plot PNG to: {plot_png_path}")
    print(f"Saved plot PDF to: {plot_pdf_path}")
    plot_class_examples_table(
        counts,
        first_images,
        table_png_path,
        table_pdf_path,
        show=args.show,
    )
    print(f"Saved table PNG to: {table_png_path}")
    print(f"Saved table PDF to: {table_pdf_path}")


if __name__ == "__main__":
    main()
